# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 148abb38982f54e53d54e4cba0e8d85a7e6f1c7e46d49bcc69494c2f72a27a5025c5fc615d6e7bb1f4aea3825823faff4434ea4b0b2f1473afa9da6fd21dc0b4

test:
  secret_key_base: 8224aa8b0b03bdd58372276ed9872ede153d5ff54a04fd67acaf7570951167ccd6a229b231d4bb96f561bf1419330dae5b7e5463b9bd88693c0c92abd80e40a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
